export const CATEGORYS_LIST_REQUEST = 'CATEGORYS_LIST_REQUEST';
export const CATEGORYS_LIST_SUCCESS = 'CATEGORYS_LIST_SUCCESS';
export const CATEGORYS_LIST_FAIL = 'CATEGORYS_LIST_FAIL';

export const CATEGORYS_DETAILS_REQUEST = 'CATEGORYS_DETAILS_REQUEST';
export const CATEGORYS_DETAILS_SUCCESS = 'CATEGORYS_DETAILS_SUCCESS';
export const CATEGORYS_DETAILS_FAIL = 'CATEGORYS_DETAILS_FAIL';

export const CATEGORYS_CREATE_REQUEST = 'CATEGORYS_CREATE_REQUEST';
export const CATEGORYS_CREATE_SUCCESS = 'CATEGORYS_CREATE_SUCCESS';
export const CATEGORYS_CREATE_FAIL = 'CATEGORYS_CREATE_FAIL';

export const CATEGORYS_DELETE_REQUEST = 'CATEGORYS_DELETE_REQUEST';
export const CATEGORYS_DELETE_SUCCESS = 'CATEGORYS_DELETE_SUCCESS';
export const CATEGORYS_DELETE_FAIL = 'CATEGORYS_DELETE_FAIL';

export const CATEGORYS_UPDATE_REQUEST = 'CATEGORYS_UPDATE_REQUEST';
export const CATEGORYS_UPDATE_SUCCESS = 'CATEGORYS_UPDATE_SUCCESS';
export const CATEGORYS_UPDATE_FAIL = 'CATEGORYS_UPDATE_FAIL';
export const CATEGORYS_UPDATE_RESET = 'CATEGORYS_UPDATE_RESET';